## The `statnet` Project
  
All `statnet` packages are open-source, written for the **R** computing
environment, and published on CRAN.  The source repositories are hosted on [GitHub](https://github.com/statnet).   Our website is [statnet.org](http://statnet.org/)

* Need help?  For general questions and comments, please email the statnet users group 
[mailing list](https://statnet.org/trac/wiki/FrequentlyAskedQuestions#statnetusersgroup).  (Note you'll need to join first)

* Found a bug in our software? Please let us know by filing an issue in the appropriate package [GitHub repository](https://github.com/statnet), with a reproducible example.

* Want to request new functionality?  We welcome suggestions -- you can make a request by filing an issue on the appropriate package [GitHub repository](https://github.com/statnet).  The chances that this functionality will be developed are substantially improved if the requests are accompanied by some proposed code (we are happy to review pull requests).  

* For all other issues, please email us at [contact@statnet.org](mailto:contact@statnet.org).
